# This workflow will create executables after pushing to github

name: Package Application with Pyinstaller

on:
  push:
    tags:
      - "*"
  workflow_dispatch:


jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Package Application
      uses: JackMcKew/pyinstaller-action-windows@main
      with:
        path: .

    - name: Archive Release
      uses: thedoctor0/zip-release@0.7.5
      with:
        type: 'zip'
        filename: 'windows exe.zip'
        directory: ./dist/windows
      
    - name: Upload Release
      uses: ncipollo/release-action@v1.12.0
      with:
        artifacts: "release.zip"
        tag: "Latest"
        token: ${{ secrets.GITHUB_TOKEN }}

